//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DONDE_INVIERTO.ANTLR
{
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="gramaticaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IgramaticaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>suma</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuma([NotNull] gramaticaParser.SumaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>suma</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuma([NotNull] gramaticaParser.SumaContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivision([NotNull] gramaticaParser.DivisionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivision([NotNull] gramaticaParser.DivisionContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>parentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentesis([NotNull] gramaticaParser.ParentesisContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentesis([NotNull] gramaticaParser.ParentesisContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>indicador</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndicador([NotNull] gramaticaParser.IndicadorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>indicador</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndicador([NotNull] gramaticaParser.IndicadorContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumero([NotNull] gramaticaParser.NumeroContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumero([NotNull] gramaticaParser.NumeroContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>resta</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResta([NotNull] gramaticaParser.RestaContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>resta</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResta([NotNull] gramaticaParser.RestaContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>producto</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProducto([NotNull] gramaticaParser.ProductoContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>producto</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProducto([NotNull] gramaticaParser.ProductoContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum([NotNull] gramaticaParser.NumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum([NotNull] gramaticaParser.NumContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] gramaticaParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] gramaticaParser.ExprContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="gramaticaParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] gramaticaParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="gramaticaParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] gramaticaParser.CompileUnitContext context);
}
} // namespace ANTLR
