//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DONDE_INVIERTO.ANTLR
{
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="gramaticaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IgramaticaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>suma</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuma([NotNull] gramaticaParser.SumaContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>division</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDivision([NotNull] gramaticaParser.DivisionContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>parentesis</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentesis([NotNull] gramaticaParser.ParentesisContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>indicador</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndicador([NotNull] gramaticaParser.IndicadorContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>numero</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumero([NotNull] gramaticaParser.NumeroContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>resta</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResta([NotNull] gramaticaParser.RestaContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>producto</c>
	/// labeled alternative in <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProducto([NotNull] gramaticaParser.ProductoContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNum([NotNull] gramaticaParser.NumContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] gramaticaParser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="gramaticaParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompileUnit([NotNull] gramaticaParser.CompileUnitContext context);
}
} // namespace ANTLR
