//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DONDE_INVIERTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondicionXMetodologia
    {
        public int Id { get; set; }
        public int MetodologiaId { get; set; }
        public int CondicionId { get; set; }
    
        public virtual Metodologia Metodologia { get; set; }
        public virtual Condicion Condicion { get; set; }
    }
}
