//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DONDE_INVIERTO.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cuenta> CuentaSet { get; set; }
        public virtual DbSet<Empresa> EmpresaSet { get; set; }
        public virtual DbSet<Indicador> IndicadorSet { get; set; }
        public virtual DbSet<Metodologia> MetodologiaSet { get; set; }
        public virtual DbSet<Periodo> PeriodoSet { get; set; }
        public virtual DbSet<CuentaXPeriodo> CuentaXPeriodoSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<IndicadorXCuenta> IndicadorXCuentaSet { get; set; }
        public virtual DbSet<Condicion> CondicionSet { get; set; }
        public virtual DbSet<CondicionXMetodologia> CondicionXMetodologiaSet { get; set; }
    }
}
