//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DONDE_INVIERTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorXCuenta
    {
        public int Id { get; set; }
        public int CuentaId { get; set; }
        public int IndicadorId { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Indicador Indicador { get; set; }
    }
}
