//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\adria\OneDrive\Documentos\TP-DDS-Grupo13\TPDDS2017_GRUPO13_DONDE_INVIERTO\ANTLR\ANTLR\GMetodologias.g4 by ANTLR 4.6.4

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ANTLR.ANTLR {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GMetodologiasParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.4")]
[System.CLSCompliant(false)]
public interface IGMetodologiasListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GMetodologiasParser.metodologia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMetodologia([NotNull] GMetodologiasParser.MetodologiaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GMetodologiasParser.metodologia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMetodologia([NotNull] GMetodologiasParser.MetodologiaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="GMetodologiasParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompileUnit([NotNull] GMetodologiasParser.CompileUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GMetodologiasParser.compileUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompileUnit([NotNull] GMetodologiasParser.CompileUnitContext context);
}
} // namespace ANTLR.ANTLR
